name: staging, build, vercel

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      
      - name: deploy to Vercel
        id: branch_deploy_vercel
        run: |
          URL=$(npx vercel --confirm -n ${{ secrets.VERCEL_PROJECT_ID }} -t ${{ secrets.TOKEN_CARBON_CLIENT }} --scope ${{ secrets.VERCEL_ORG_ID }} -b DEPLOY_ENV=staging -e DEPLOY_ENV=staging)
          
